# Generated by Django 2.1.7 on 2019-03-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmail', models.EmailField(max_length=254)),
                ('tname', models.CharField(max_length=30)),
                ('tloc', models.CharField(max_length=30)),
                ('tmorn_img', models.ImageField(blank=True, upload_to='')),
                ('tmorn_name', models.CharField(max_length=30)),
                ('tafter_img', models.ImageField(blank=True, upload_to='')),
                ('tafter_name', models.CharField(max_length=30)),
                ('teve_img', models.ImageField(blank=True, upload_to='')),
                ('teve_name', models.CharField(max_length=30)),
                ('tcost', models.IntegerField(default=150)),
            ],
        ),
        migrations.CreateModel(
            name='Ureg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('umail', models.EmailField(max_length=254)),
                ('upass', models.CharField(max_length=30)),
                ('uphone', models.IntegerField(max_length=10)),
                ('uaddr', models.TextField()),
                ('urole', models.CharField(max_length=20)),
            ],
        ),
    ]
