# Generated by Django 2.1.7 on 2019-03-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ureg',
            name='uphone',
            field=models.TextField(max_length=10),
        ),
    ]
