# Generated by Django 2.1.7 on 2019-03-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20190322_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ureg',
            name='uphone',
            field=models.CharField(max_length=10),
        ),
    ]
