# Generated by Django 2.1.7 on 2019-03-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='m_img',
        ),
        migrations.AddField(
            model_name='movie',
            name='mimg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
