# Generated by Django 2.1.7 on 2019-03-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20190322_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='treg',
            name='tcity',
            field=models.CharField(blank=True, default='Please update theatre city', max_length=30, null=True),
        ),
    ]
