# Generated by Django 2.1.7 on 2019-03-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='slist',
            field=models.ManyToManyField(to='ticket.Movie'),
        ),
    ]
