# Generated by Django 2.1.7 on 2019-03-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_sample_slist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='slist',
            field=models.ManyToManyField(related_name='_sample_slist_+', to='ticket.Sample'),
        ),
    ]
