# Generated by Django 2.1.7 on 2019-03-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_auto_20190323_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='slist',
            field=models.ManyToManyField(to='ticket.Treg'),
        ),
    ]
