# Generated by Django 2.1.7 on 2019-03-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0017_auto_20190323_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='treg',
            name='tdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
