# Generated by Django 2.1.7 on 2019-03-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0018_treg_tdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumail', models.CharField(blank=True, max_length=30, null=True)),
                ('stname', models.CharField(blank=True, max_length=30, null=True)),
                ('stdate', models.DateField(blank=True, null=True)),
                ('sshowname', models.CharField(blank=True, max_length=30, null=True)),
                ('sshowtype', models.CharField(blank=True, max_length=30, null=True)),
                ('sslot', models.CharField(blank=True, max_length=30, null=True)),
                ('stcost', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
